### ISSUE TITLE
ユーザーからの回答を保存する箇所について

### ISSUE THREAD

**Issue by yudetamago** [morosawamikihito/TeamA-App#18]
(実装し終わってしまってから言うのもアレですが)
今の実装だと、質問一回ごとに回答を送る形になってますが、結構無理矢理な感じがするので、質問全てに答え終わったところで送るぐらいで良いかもです。
(あとそこまで考慮しなくても良い気はしますが、誤ってブラウザの更新押してしまってから回答すると重複して回答出来てしまったりするので)
最初のsinatra_appのコミットのdebugがちょうど回答をまとめて送る感じになってます。
ref. https://github.com/morosawamikihito/TeamA-App/blob/a6033ca5d81681a4063086609ce4130f63f8b901/sinatra_app/views/index.erb#L24
こうするとサーバサイドのほうも回答の保存を最後にまとめてするだけになるので実装が楽になるかと思います。

**Comment by yudetamago** [comment]
適当な例ですが、

```ruby
answers =  [
  {"id": 1, "score": 2},
  {"id": 2, "score": 3},
  {"id": 3, "score": 4},
  {"id": 4, "score": 5}
]
```

だったら

```ruby
csv =["id", "score"].to_csv + answers.map(&:values).map(&:to_csv).join
File.write('name.csv', csv)
```

ぐらいのコード量になるかなと思います。

**Comment by morosawamikihito** [comment]
なるほど！
少し疑問なんですが、
```
answers =  [
  {"id": 1, "score": 2},
  {"id": 2, "score": 3},
  {"id": 3, "score": 4},
  {"id": 4, "score": 5}
]
```
の"score"についてですが、四択のボタンのどれかが押下されたら値が変化しなければいけないと思うのですが、どのようにして変化させるのかと、結果の送信ボタンがクリックされるまでどのようにして値を保持するのかが分からないのですが...。

**Comment by yudetamago** [comment]
フロントエンド(つまりJS)でやる感じになると思います〜

**Comment by morosawamikihito** [comment]
明日中にはfixしときますー！

**Comment by yudetamago** [comment]
UIが出来てからまた色々調整すると思うので、そこまで作り込まなくてもだいたいで大丈夫ですー！

**Comment by yudetamago** [comment]
ここのコミットのやつ読みました。
サーバサイドでは`/start`、`/answer`それぞれのファイル書き込みで、フロントエンドではDOMで状態管理をしていて、状態管理がサーバサイドとフロントエンド両方に分かれてしまって以前よりかえって複雑になってしまっている気がするので(UI次第ですが)適当に簡単なコード書きます。
たぶんフロントエンド側に寄せるのが楽そうな気がしてます。

（この辺、ただ動かす分には普通に動きそうですが、チーム開発なので良いところを共有出来たらと思います）
