### ISSUE TITLE
近い質問を取得する箇所のエラーについて

### ISSUE THREAD

**Issue by yudetamago** [morosawamikihito/TeamA-App#19]
(まだ実装途中だったら申し訳ないです)

レアなケースだとは思いますが、
https://github.com/morosawamikihito/TeamA-App/blob/master/sinatra_app/domain/answer.rb#L60
のところで`nearer_questions`の数が足りないとエラーになりそうです。
念のため。

**Comment by morosawamikihito** [comment]
なるほど、確かにそうですね...。
ありがとうございます
